# .github/actions/install-mac-dependencies/action.yml

name: 'Install Mac Dependencies'
description: 'Installs the Mac Dependency for Yuyan'
runs:
  using: 'composite'
  steps:
    - name: brew install
      run: |
        brew install bdw-gc libuv mlton llvm
        echo "/usr/local/opt/llvm/bin:$PATH" >> $GITHUB_ENV
      shell: bash