# .github/actions/install-mac-dependencies/action.yml

name: 'Install Linux Software'
description: 'Installs Linux Yuyan Dependencies'
runs:
  using: 'composite'
  steps:
    - name: Install MLTon
      run: |
          wget https://phoenixnap.dl.sourceforge.net/project/mlton/mlton/20210117/mlton-20210117-1.amd64-linux-glibc2.31.tgz
          tar -xvzf mlton-20210117-1.amd64-linux-glibc2.31.tgz
          cd mlton-20210117-1.amd64-linux-glibc2.31/
          sudo make
          sudo make install
      shell: bash
    - name: Install the libraries
      run: |
        sudo apt install libgc-dev libuv1-dev llvm libbsd-dev
      shell: bash